### ISSUE TITLE
JW300 Link Broken in README

### ISSUE THREAD

**Issue by jowodo** [GhanaNLP/kasa#31]
I could not open the following link: https://www.kaggle.com/azunre/jw300entw
Where can I find the JW300 en-twi data set? 

Thanks!

**Comment by azunre** [comment]
Hello, unfortunately the owners of the JW300 data contacted us to take it down. If you look around the internet you will see it is no longer available anywhere. Unfortunately, there isn't anything we can do about this for now, except update the README to indicate this,

**Comment by jowodo** [comment]
That is unfortunate. But thanks for the more than quick reply! 
EDIT: corrected typo

**Comment by PhidLarkson** [comment]
@jowodo hello man, found this Dr. Azunre's page

![image](https://github.com/user-attachments/assets/2d0303ed-4afa-4255-9a4a-53057cc4cabd)
You might want to check this out.

[Dataset](https://www.kaggle.com/datasets/azunre/twi-dataset)
