### ISSUE TITLE
Integrate BERT models into Kasa lib

### ISSUE THREAD

**Issue by joelbudu** [GhanaNLP/kasa#8]

**Comment by hotlynnn** [comment]
BERT models have been integrated into Kasa library, but not running on production since it's in the test.pypi.org repo

pip install -i https://test.pypi.org/simple/ Kasa

Run this in your anaconda prompt and see if there will be no errors aside library dependencies

**Comment by MarkMarcel** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/45716888/107966269-83694a00-6fa3-11eb-88ae-e6db1965aa9e.png)
I tried to run the pip command and this is what I got.

I am new to the anaconda thing

**Comment by joelbudu** [comment]
@Hotlynn2  Do we have this on a particular branch please?

**Comment by hotlynnn** [comment]
@joelbudu Not yet 
I will do that soon
I want us to finish with the testing, move the library to the main pypi repo,
Then I commit it to the Ghana NLP github page

**Comment by joelbudu** [comment]
You should have your developments on a feature branch (not master) so others can easily help and progress is visible. You don't have to wait until you're done please.

**Comment by hotlynnn** [comment]
Alright
I will do that

**Comment by MarkMarcel** [comment]
Hello @Hotlynn2, seems the version of torch the Kasa library depends on is not available for download again from pypi
![Screenshot (8)](https://user-images.githubusercontent.com/45716888/109959357-43160580-7cdf-11eb-964a-4fde6f0bfc3a.png)

**Comment by hotlynnn** [comment]
Let's have a look at it when you have time. When can that be please?

**Comment by hotlynnn** [comment]
The preprocessing.py is functioning nd in the pypi.org repo. Please check and move it to the master branch. You can check by using

pip install Kasa
@joelbudu 
@MarkMarcel 

Please check if the requirement gensim is being installed automatically

**Comment by hotlynnn** [comment]
Joel closed the issue Mark. Let me know when you are less busy so that we look at the ABENA models
