### ISSUE TITLE
Create API for Translation app using appropriate Azure feature/services

### ISSUE THREAD

**Issue by joelbudu** [GhanaNLP/kasa#9]
The goal of this is to migrate the current translation app using an appropriate Azure service. (Functions for example)

Acceptance Criteria

1. Automatically scalable to serve a large number of requests
2.  Feature Rate-limiting to prevent over-loading of the service
3. Quick response time
4. Input Validation and Error-handling
5. Authentication (Optional for now)

You will need to request for access to the current github repository to start working on this. Please contact me.

**Comment by joelbudu** [comment]
@benadaba  @DanielKomlaElijah  
What's the update on this task please?

**Comment by DanielKomlaElijah** [comment]
https://testtransapi.azurewebsites.net/translate/api/docs/

**Comment by joelbudu** [comment]
Hosting this application on a ghananlp domain now:

https://translation-api.ghananlp.org/translate

**Comment by joelbudu** [comment]
We'll be using the Azure API management service to manage products, subscriptions, quotas, rate limiting etc.

**Comment by joelbudu** [comment]
https://translation-api0.developer.azure-api.net/
